// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoG0SxUImgs48mULqnUYfDb9xthXfYxus',
    appId: '1:160043964806:web:8a8af1afc2660dd7437407',
    messagingSenderId: '160043964806',
    projectId: 'hunchapp-68c9f',
    authDomain: 'hunchapp-68c9f.firebaseapp.com',
    storageBucket: 'hunchapp-68c9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3slJH-p2f1DYkWlPEeLupm_k_DS3mI4',
    appId: '1:160043964806:android:e7914dc3544c30f3437407',
    messagingSenderId: '160043964806',
    projectId: 'hunchapp-68c9f',
    storageBucket: 'hunchapp-68c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfsvILNoX8LF5mfZMgf-GYVTxWtJE3ylg',
    appId: '1:160043964806:ios:b08363df9479fc8a437407',
    messagingSenderId: '160043964806',
    projectId: 'hunchapp-68c9f',
    storageBucket: 'hunchapp-68c9f.appspot.com',
    iosBundleId: 'com.example.hunchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfsvILNoX8LF5mfZMgf-GYVTxWtJE3ylg',
    appId: '1:160043964806:ios:19a3a8726b3d0cc6437407',
    messagingSenderId: '160043964806',
    projectId: 'hunchapp-68c9f',
    storageBucket: 'hunchapp-68c9f.appspot.com',
    iosBundleId: 'com.example.hunchApp.RunnerTests',
  );
}
